### ISSUE TITLE
请问这种加载初始化的时候出现一个很高的灰框子,怎么将其去除

### ISSUE THREAD

**Issue by yymmhh** [csonchen/wx-minicomponent#1]
请问这种加载初始化的时候出现一个很高的灰框子,怎么将其去除,或者高度调整小一点,加载的是一个图片手机号码.找到去除灰色背景的地方了.

![image](https://user-images.githubusercontent.com/34824081/91517833-62dc0380-e921-11ea-85f6-83c7329ca5a1.png)

**Comment by csonchen** [comment]
@yymmhh 你这边可以提供一段html富文本给我调试吗

**Comment by csonchen** [comment]
我这边设置了一个默认的高度用来作为图片加载前的占位符，因为图片加载完毕之后才能获取到图片的实际宽高，没法在图片加载前就能设置展位图片的宽高，有点麻烦

**Comment by yymmhh** [comment]
`<img src='https://91caiqing.com/content/common/contact_img?text=eyJpdiI6ImdnY3owbjVQOHB1SStLcWpNcHlDeUE9PSIsInZhbHVlIjoidDNqSDY1OURwenFra0lrNzcwemZBQT09IiwibWFjIjoiM2YzMWM4YzJjZDlhOTY5YjkyMGQ1ZGY2OTgwZjE5MTNjNmM0MjY3YWFkYTlhMTA4NzZkMzVhZjk0MmZlMzY1ZiJ9&type=phone' />`

这样的html

我手动做了延时展示,看起来好点了

**Comment by yymmhh** [comment]
`<img src='https://91caiqing.com/content/common/contact_img?text=eyJpdiI6IjZZazkrYUd1bWwyVTRld20xcXNVaXc9PSIsInZhbHVlIjoiWGxsMDlhSkR0Wm0yYkpLZ3BLcnFrZz09IiwibWFjIjoiNTBkM2Q1NzJlOTQ0ZTIzZjM3ZWViYzNmZmRlZmE1OWZiNmYwYWE4YzM3ZWY1N2IyNTQ5NjMzNzM5ODE0MjY0NyJ9&type=phone' />`

<img src='https://91caiqing.com/content/common/contact_img?text=eyJpdiI6IjZZazkrYUd1bWwyVTRld20xcXNVaXc9PSIsInZhbHVlIjoiWGxsMDlhSkR0Wm0yYkpLZ3BLcnFrZz09IiwibWFjIjoiNTBkM2Q1NzJlOTQ0ZTIzZjM3ZWViYzNmZmRlZmE1OWZiNmYwYWE4YzM3ZWY1N2IyNTQ5NjMzNzM5ODE0MjY0NyJ9&type=phone' />

这样的html

我手动做了延时展示,看起来好点了

**Comment by csonchen** [comment]
就是这个图本身太小，但是灰色占位符的太大，造成视觉差导致的，但是没办法在图片加载完毕之前获取到图片的实际宽高
